---

- name: "Count test id lines of {{ log_file }}"
  command: "wc -l {{ log_file }}"
  register: log_file_result
  changed_when: False
  become: yes
  when: write_test_log

- name: Define log_lines
  set_fact:
    log_lines: "{{ log_file_result.stdout.split()[0] }}"
  when: write_test_log

- name: "id user {{ item.username }}"
  command: "id {{ item.username }}"
  ignore_errors: true
  changed_when: False

- name: Define log_test_file
  set_fact:
    log_test_file: "{{ log_path + '/' + 'test-id-user.' + ( item.username | string ) + '.log' }}"
  when: write_test_log

- name: Define log_id_files
  set_fact:
    log_id_files: "{{ log_id_files + [ log_test_file ] }}"
  when: write_test_log

- name: "Copy test id lines of {{ log_file }} to {{ log_test_file }}"
  shell: "tail -n +{{ log_lines }} {{ log_file }} > {{ log_test_file }}"
  changed_when: False
  become: yes
  when: write_test_log
